name: k6-load-tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          k6 run tests/k6/stayas-auth.test.js